 export interface User{
    studyGuideTimeSpent?: number,
    practiceAssessmentsCompleted?: number,
    focusedReviewTimeSpent: string,
    sgLearner?: number,
    frLearner?: number,
    peLearners?: number,
    assessmentLearners?: null,
    completedAssessments?: null,
    baselineAssessmentLearners?:string,
    finalAssessmentLearners?: string,
    essentialSkillLearners?: string,
    assessments?: null,
    practiceSimulations?: string,
    timeSpent?: string,
    usage?: string,
    variance?: null,
    activitiesCompleted?: null,
    showUsageTrend?: true,
    mobileFlashCardTimeSpent?: string,
}